# Generated by Django 4.1.7 on 2023-03-28 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_alter_presentation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='status',
            field=models.ForeignKey(default='SUBMITTED', on_delete=django.db.models.deletion.PROTECT, related_name='presentations', to='presentations.status'),
            preserve_default=False,
        ),
    ]
