# Generated by Django 4.1.7 on 2023-03-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_alter_accountvo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
